/**
 * @overview generated by ghoti-cli
 * @fileoverview Webpack Config Renderer Production
 */

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

const BUILD_DIR = path.resolve(__dirname, '..', 'app', 'anotherone');
const APP_DIR = path.resolve(__dirname, '..', 'src', 'anotherone');
const PUBLIC_DIR = path.resolve(__dirname, '..', 'public', 'buildTemplate.html');
const PAGECLIP_DIR = path.resolve(__dirname, '..', 'public', 'pageclip.html');
const RENDERERTSCONFIG_DIR = path.resolve(__dirname, 'tsconfigParser.json');

let config = {
    devtool: 'cheap-source-map', // for debug
    entry: {
        index: APP_DIR + "/index.tsx",
        // report: APP_DIR + "/bugReport/index.tsx",
    },
    target: "electron-renderer",
    output: {
        filename: "[name].bundle.js",
        path: BUILD_DIR
    },
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx", ".js", ".json", ".css", ".sass"]
    },
    module: {
        rules: [
            // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
            {
                test: /\.tsx?$/,
                use: [{
                    loader: 'awesome-typescript-loader',
                    options: {
                        configFileName: RENDERERTSCONFIG_DIR
                    }
                }]
            },
            {
                test: /\.sass$/,
                use: [
                    'style-loader',
                    'css-loader',
                    'sass-loader'
                ]
            },
            {
                enforce: "pre",
                test: /\.js$/,
                loader: "source-map-loader",
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            chunks: ['index'],
            title: 'p6',
            template: PUBLIC_DIR,
            filename: 'index.html',
        }),
        // new HtmlWebpackPlugin({
        //     chunks: ['report'],
        //     title: 'p6',
        //     template: PAGECLIP_DIR,
        //     filename: 'report.html',
        // }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production')
        }),
        new UglifyJSPlugin()
    ]
};

module.exports = config;