/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set Dropper
 */

import * as React from 'react';

import DropZone from 'react-dropzone';
import Config from '../../config/config';

import * as fs from 'fs';
import * as path from 'path';

export interface IProps {
    onDrop: (path: string) => void;
    load: string;
    children?: any;
}

class Dropper extends React.Component<IProps, {}> {
    public constructor(props) {
        super(props);
        this.onDrop = this.onDrop.bind(this);
    }

    public render() {
        return (
            <DropZone
                onDrop={this.onDrop}
                title="add pictures"
                width={150}
                height={100}
                className="drag-in">
                {this.props.load ? <i className="fas fa-image"></i> : <i className="far fa-image"></i>}
            </DropZone>);
    }

    protected onDrop(acceptedFiles: File[], rejectedFiles) {
        if (acceptedFiles.length > 0) {
           
            const file=acceptedFiles[0];
            this.props.onDrop((file as any).path);
            }

        }
      

}

export default Dropper;
