/**
 * @overview generated by ghoti-cli
 * @fileoverview Page Index
 */

import { ipcRenderer, shell } from "electron";

import * as React from "react";

import "./global.sass";

class Hello extends React.Component<{}, {}> {

    public constructor(props: {}) {
        super(props);
    }

    public render(): any {
        return (
            <React.Fragment>
                <form action="https://send.pageclip.co/IYHgSb0migBy6AIR2gwYY0us6VlyrPjd" className="pageclip-form" method="post">
                    <input type="text" name="name" />
                    <input type="email" name="email" />
                    <button type="submit" className="pageclip-form__submit">
                        <span>Send</span>
                    </button>
                </form>
            </React.Fragment>
        );
    }
}

export default Hello;
