/**
 * @overview generated by ghoti-cli
 * @fileoverview Page Entry
 */

import * as React from "react";
import * as ReactDOM from "react-dom";
import { AppContainer } from "react-hot-loader";

import Hello from "./hello";

declare const module: any;
declare const declear: any;

const render: (App: any) => void = (App: any): void => {

    ReactDOM.render(
        <AppContainer>
            <App />
        </AppContainer>,
        document.getElementById("container"));
};

render(Hello);
if (module.hot) {

    module.hot.accept("./hello", () => {
        render(require("./hello").default);
    });
}
