/**
 * @overview generated by ghoti-cli
 * @fileoverview Config
 */

export default {
    isDebug: true,
    backgroundColor: "white",
    version: "1.4.1",
    pageclipAPIKEY: 'api_1lTukXYBULhnVY9WAouliY2AMPhzlS0w',
    pageclipVeri: 'YXBpXzFsVHVrWFlCVUxoblZZOVdBb3VsaVkyQU1QaHpsUzB3Og',
};
