/**
 * @author WMXPY
 * @overview generated by ghoti-cli
 * @fileoverview Component set ComponentGhotiLunuh
 */

import * as React from 'react';

import '../../style/lunuh.sass';

class ComponentGhotiLunuh extends React.Component<{
    style?: any;
}, {}> {
    public constructor(props) {
        super(props);
    }

    public shouldComponentUpdate() {
        return false;
    }

    public render() {
        return (
            <svg width="50" viewBox="0 0 560 100" className="lunuh-svg" style={this.props.style}>
                <polygon points="0,0 0,100 100,100 100,0" className="lunuh-polygon" />
                <polygon points="150,0 150,100 250,100" className="lunuh-polygon" />
                <polygon points="230,0 330,0 330,100" className="lunuh-polygon" />
                <polygon points="380,0 380,100 480,100" className="lunuh-polygon" />
                <polygon points="460,0 560,0 560,100" className="lunuh-polygon" />
            </svg>
        );
    }
}
/* <div style={{
                fontSize: '8px',
            }}>Think {['Parallelogram', 'Same', 'Deadend', 'Complex', 'Recursive', 'Limited', 'Hopeless'][Math.floor(Math.random() * 7)]}</div> */

export default ComponentGhotiLunuh;
